### ISSUE TITLE
Unexpected behavior on http.post requests 

### ISSUE THREAD

**Issue by RafRoq** [dart-lang/http#720] opened 2022-06-17 03:26 UTC
i have a python code using python requests that makes a request like this: ```request.post(url, {'requisicao': SomeNumber})```
it works and returns me the page to scrape or do whatever i want

when doing the same on dart using: ```http.post(url, {'requisicao': SomeNumber})```
it gives me status code 500, does not work, someone told me to change it to: ```client.post(uri, body: jsonEncode({'requisicao': SomeNumber}));``` this way it returns me something but still does not work as expected, returns me something different from the python one, makes me think there is something that python does and dart does not, on post requests, that makes python work and dart not work.

the server i'm trying to access isn't mine, it doesnt say to me what went wrong it just happens wrong and i notice seeing the result

**Comment by osa1** [comment] 2022-07-13 12:14
Could you compare the HTTP headers and contents sent to the server by Dart and Python applications? A tool like WireShark should help with watching the HTTP traffic and comparing them.

I wonder if this could be a missing Content-Type header in the Dart version. Documentation of `post` says:

```
  /// Sends an HTTP POST request with the given headers and body to the given
  /// URL.
  ///
  /// [body] sets the body of the request. It can be a [String], a [List<int>]
  /// or a [Map<String, String>].
  ///
  /// If [body] is a String, it's encoded using [encoding] and used as the body
  /// of the request. The content-type of the request will default to
  /// "text/plain".
  ///
  /// If [body] is a List, it's used as a list of bytes for the body of the
  /// request.
  ///
  /// If [body] is a Map, it's encoded as form fields using [encoding]. The
  /// content-type of the request will be set to
  /// `"application/x-www-form-urlencoded"`; this cannot be overridden.
  ///
  /// [encoding] defaults to [utf8].
  ///
  /// For more fine-grained control over the request, use [send] instead.
```

In your case, `body` is a `String` so the content-type will be text/plain. The server probably wants application/json. Could you try `http.post(url, body: jsonEncode(...), headers: {'content-type': 'application/json'})`? Hopefully that won't add double quotes in the HTTP body..

**Comment by natebosch** [comment] 2022-08-17 19:37
Closing for now since this issue is not actionable.

If you have a reproduction case and can describe how the HTTP request differs from your expectations we can take another look.

**Closed by natebosch** 2022-08-17 19:37 UTC
Labels: question
