### ISSUE TITLE
Throws ClientExeption if I try connecting to localhost '10.0.2.2' but works fine with other urls

### ISSUE THREAD

**Issue by MuhammedKasujja** [dart-lang/http#259] opened 2019-03-16 12:36 UTC

**Comment by MuhammedKasujja** [comment] 2019-03-16 12:39
I have been doing this for almost 3 days now but the same issue. Please I need your help my project is now at a stand-still.

**Comment by idealopamp** [comment] 2019-04-03 01:47
I am experiencing the same problem.  It also manifests in other real-world scenarios, such as the server closing the connection abruptly.  The problem is made worse by the fact that ClientException does not appear to be exposed externally, so there is no way to catch the exception.

**Comment by natebosch** [comment] 2019-04-16 23:07
This is a local environment issue and is not caused by this package - we are wrapping the clients from `dart:io` or `dart:html`. If you hit this with `HttpClient` from `dart:io` but don't hit it when trying to connect with non-dart clients (like `curl`) and believe there is a bug with the VM you can file an issue at https://github.com/dart-lang/sdk/issues

**Closed by natebosch** 2019-04-16 23:07 UTC
