### ISSUE TITLE
XMLHttpRequest error

### ISSUE THREAD

**Issue by floitschG** [dart-lang/http#67] opened 2017-03-15 15:21 UTC
_From @SadovovAlex on March 14, 2017 12:7_

if response this format or other json:
{"listFias":[],"status":"NotFound"}

i recieved error:
XMLHttpRequest cannot load http://0001qwerty02:8888 

``` dart
  var client = new BrowserClient();
  var url = '/whatsit/create';
  var response =
      await client.post(url, body: {'name': 'doodle', 'color': 'blue'});
  print('Response status: ${response.statusCode}');
  print('Response body: ${response.body}');
```

_Copied from original issue: dart-lang/sdk#29068_

**Comment by nex3** [comment] 2017-05-15 19:10
Have you tried making the request with the plain [`HttpRequest`](https://api.dartlang.org/stable/1.23.0/dart-html/HttpRequest-class.html) class? If that reproduces the error, it's not related to the `http` package.

**Comment by david-onehub-dev** [comment] 2018-03-22 14:30
we ran into this XMLHttpRequest error when oauth token is expired. browser client is unable to capture http request 401 and return response. Instead, ClientException is thrown from http pacakge.

**Comment by nex3** [comment] 2018-03-22 18:16
@david-onehub-dev Same question: what happens when you make the request with a plain [`HttpRequest`](https://api.dartlang.org/stable/1.23.0/dart-html/HttpRequest-class.html)? And what exception is being thrown?

**Comment by krel024** [comment] 2019-01-16 11:00
Hi, I'm still having this problem only when I use cross domain request.

http.get('https://api.domain.com/non-exists-path');

This will throw a XMLHttpRequest error instead of return a Response object with status code 404.

What I can do?

**Comment by AppleEducate** [comment] 2019-06-18 16:30
This happens when I postUrl.

```dart
    var client = new http.Client();

    final _body = {
      "grant_type": "password",
      "username": _username.text,
      "password": _password.text,
    };

    await updateLog(_body.toString(), duration: Duration(seconds: 2));

    try {
      final _data = await client.post(url, body: _body, headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
      });
      await updateLog(_data.toString(), duration: Duration(seconds: 2));
    } catch (e) {
      await updateLog('Post Error..', duration: Duration(seconds: 1));
      await updateLog(e.toString(), duration: Duration(seconds: 1));
    }
```

**Comment by cskau-g** [comment] 2019-06-19 08:26
This looks like [a known limitation in the BrowserClient](https://github.com/dart-lang/http/blob/master/lib/src/browser_client.dart#L78-L84) (seemingly based on a known limitation in XHR):
```
      // Unfortunately, the underlying XMLHttpRequest API doesn't expose any
      // specific information about the error itself.
      completer.completeError(
          ClientException("XMLHttpRequest error.", request.url),
          StackTrace.current);
```

XHR's onerror is fired for _network-level_ errors (i.e. where there is no HTTP response code).
This might seem contrary to what you're seeing when the network tab shows 404, but for CORS error this makes sense since the browser does see the 404, but then decides to block the response from reaching the application based on the missing CORS headers.
From the application's PoV there was no 404, only network error. Hence there is only the generic "XMLHttpRequest error" to fall back on.

From a dev's perspective this is a generic network error caused by CORS, which needs to be fixed on the server side.

As for this issue I'd say this is all WAI in the context of the limitations imposed by XHR and CORS.

**Comment by AppleEducate** [comment] 2019-06-19 11:17
Gotcha. Yeah I have building Flutter apps for desktop and mobile and it’s just now when running the apps in the browser where it started breaking. Specifically logging in. So I am use firebase now as a proxy server

**Comment by cskau-g** [comment] 2019-06-21 08:22
I'm closing this issue since the original issue hasn't been updated since 2017 and the pings since then seem to be explained by https://github.com/dart-lang/http/issues/67#issuecomment-503461018

**Closed by cskau-g** 2019-06-21 08:22 UTC
Labels: need-info, type-bug

**Comment by sh0umik** [comment] 2020-01-10 03:04
I need to test this in Browser ? Any Solution without hosting it in firebase ?

**Comment by sashvoncurtis** [comment] 2020-03-17 21:34
Hi, 

I've seen this question come up a lot, and would imagine others will encounter the same response error.
It's usually to do with trying to run a "concurrent" server and client, but both from different 'servers', like flutter run -d chrome and dart bin/server.dart.

Other than VSCode's  launch.json I have not seen something like concurrently (npm) to run main.dart and server.dart. 

Would be awesome to see a solution to this, especially as the web branch matures.

**Comment by syleishere** [comment] 2021-03-24 01:24
Response code comes back null when using flutter web(browser), this is why this is happening.
