### ISSUE TITLE
The HTTP request is not being executed in response

### ISSUE THREAD

**Issue by geeksilva97** [dart-lang/http#384] opened 2020-02-17 18:49 UTC
I'm trying to perform a request to a Web API written in C# (.NET Core). The endpoint runs a async function and return a JSON with result of operation.

In Dart I can't get the response. **then()** or **catchError()** just don't executes. 

The endpoint get products in payload. When I send only one product I can get the response but when ai send two or more I can't.

The payload is:

```dart
http .post('http://192.168.0.10:5000/api/v1/oficina/dart',
                  body: jsonEncode({
                    "usuario": "edigleyssonsilva",
                    "senha": "123456",
                    "codEmp": 1,
                    "codFil": 1,
                    "produtos": [
                      {
                        "ccuRes": "160",
                        "codEmp": 1,
                        "codFil": 1,
                        "codPro": "570.0001",
                        "codTns": "90250",
                        "datPrv": "2020-02-17",
                        "datEme": "2020-02-17",
                        "qtdEme": 2
                      },
                      // {
                      //   "ccuRes": "160",
                      //   "codEmp": 1,
                      //   "codFil": 1,
                      //   "codPro": "570.0008",
                      //   "codTns": "90250",
                      //   "datPrv": "2020-02-17",
                      //   "datEme": "2020-02-17",
                      //   "qtdEme": 2
                      // },
                      // {
                      //   "ccuRes": "160",
                      //   "codEmp": 1,
                      //   "codFil": 1,
                      //   "codPro": "570.0011",
                      //   "codTns": "90250",
                      //   "datPrv": "2020-02-17",
                      //   "datEme": "2020-02-17",
                      //   "qtdEme": 1
                      // }
                    ]
                  }),
                  headers: {'Content-Type': 'application/json'})
              .then((value) => print(value.body))
              .catchError((err) {
                print('Ocorreu um erro');
                print(err);
              });
```

The commented lines are other products, when I uncomment the requiest cannot get response.

The method that runs in API is:

![image](https://user-images.githubusercontent.com/15680379/74679501-bfa17900-519c-11ea-9d00-7c4397a95f9c.png)

Please. I need help!

**Comment by geeksilva97** [comment] 2020-02-17 18:50
I already tested the same endpoint with the same payload on Postman and Angular app and this works perfectly.

So I have no ideia why this not works in Dart.

**Comment by srburton** [comment] 2020-02-24 15:43
For some reason, this only happens when in the emulator, I tested it via USB depreciation on my xiaomi REDMI note 4x device, the requests worked perfectly. Now it gets even weirder.

**Comment by tiagoagenor** [comment] 2020-03-17 22:00
I have the same problem. I can't solve it. Has anyone managed to solve?

**Comment by geeksilva97** [comment] 2020-03-18 11:19
> For some reason, this only happens when in the emulator, I tested it via USB depreciation on my xiaomi REDMI note 4x device, the requests worked perfectly. Now it gets even weirder.

I tested on real device too. I'm still having problem.

**Comment by talregev** [comment] 2021-06-12 19:28
I have the same problem. Happen for me with windows, uwp and android app. (Work perfect on web).
I do an `http.post(...)` and never get the response. not by await, not by then. I know my code is working, because it working on flutter web application, also it work from postman. 
Any news?

**Comment by talregev** [comment] 2021-07-01 04:03
I understand why http post doesn't work on windows on some of the server.
in http that come from dart.io (all application except web), it not add in the header `Content-Length:` also if force all the header to be lowercase, while http header is sensitive case. it not happen in http web.

**Comment by hgouveia** [comment] 2021-09-09 12:36
same issue, first request works just fine, but the second request it just keep for forever , never pass the Await or Then , not Catch either, never get the response. if i execute the same request in Postman, works everytime, so is not the server

**Comment by natebosch** [comment] 2021-09-09 19:18
> in http that come from dart.io (all application except web), it not add in the header `Content-Length:` also if force all the header to be lowercase, while http header is sensitive case.

I assume this is the problem in all reported instances. The server you are interacting with is not compliant with the Http spec and is not reading the content length header with case insensitivity. The feature request for adding direct support for preserving header case in order to interact with these buggy servers is https://github.com/dart-lang/http/issues/609 so I'll close this as a duplicate for now.

In the meantime you can use `dart:io` directly and pass the `preserveHeaderCase` argument when setting headers that are case sensitive on the server side. https://api.dart.dev/stable/2.14.1/dart-io/HttpHeaders/set.html

**Closed by natebosch** 2021-09-09 19:18 UTC

**Comment by hgouveia** [comment] 2021-09-09 19:26
In my case I am sending Request to twitter api, that I asume they have proper http spec in place, and this will explain if the request never succed but in my case the first Request works and if I call the same one again is not working anymore just waiting for ever the response

**Comment by natebosch** [comment] 2021-09-09 20:04
@hgouveia - have you tried the requests using the client from `dart:io` directly to confirm if there is a bug in this library?

Do you have a complete minimal reproduction case you can share?

**Comment by hgouveia** [comment] 2021-09-10 16:11
> @hgouveia - have you tried the requests using the client from `dart:io` directly to confirm if there is a bug in this library?
> 
> Do you have a complete minimal reproduction case you can share?

Hello @natebosch  my request is very simply really 

```dart
http.Response response = await http.get(url, headers: {'Authorization':  '....' });
```

But it seems i solved the issue because now i get response every time, i am not totally  sure, i am using flutter and i recently upgrade the flutter sdk, and one of the [steps ](https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects)  was to remove some line, but it seems this line caused the issue, since i put it back, and now seems to be working fine or could be tottally coincidece , anyways i dont have the issue anymore, thanks!

![image](https://user-images.githubusercontent.com/668866/132884198-04c579d8-f045-4d9a-8e47-ca77c308a6d3.png)
