### ISSUE TITLE
multi set-cookie

### ISSUE THREAD

**Issue by ozgungunay** [dart-lang/http#462] opened 2020-08-23 21:12 UTC
if there is multi set-cookie in response header, only firsth one set. The second one can not be seen in response header.
Especially when flask server send a session in  set-cookie, I can not see in response header.

**Comment by catherinezhxj** [comment] 2021-09-09 06:53
> if there is multi set-cookie in response header, only firsth one set. The second one can not be seen in response header.
> Especially when flask server send a session in set-cookie, I can not see in response header.

I have the same problem. How did you finally solve it  in flask server?

**Comment by shalien** [comment] 2022-09-10 08:13
Actually had the issue with a Laravel based app and it seem that the set-cookie header are merged together and separated by an ,

**Comment by brianquinlan** [comment] 2024-01-12 21:31
This is a duplicate of https://github.com/dart-lang/http/issues/24

**Closed by brianquinlan** 2024-01-12 21:31 UTC
