### ISSUE TITLE
Inconsistency between http dart.library.io and  dart.library.html

### ISSUE THREAD

**Issue by talregev** [dart-lang/http#589] opened 2021-07-01 04:10 UTC
http that come from dart.library.io  (all application except web):
It not add in the header `Content-Length:` also if force all the header to be lowercase, while http header is sensitive case.
This break the connection to legacy http server that expect the  `Content-Length:` field in the header, while looking it as sensitive way. (exact as I write it). also looking other fields header in sensitive way. 
In http that come from dart.library.html (the web application):
It add automatically the  `Content-Length:` and not force the header to be lowercase.  
This Inconsistency is bad. All application across platforms should do the same http request. The http request should be as you doing in dart.library.html. Please make dart.library.io http the same as dart.library.html

**Comment by natebosch** [comment] 2021-09-09 19:24
Closing as a duplicate of #609 which requests support for a `preserveHeaderCase` argument on the `IOClient`.

**Closed** 2021-09-09 19:25 UTC

**Comment by talregev** [comment] 2021-09-09 19:26
What about `Content-Length:`? Don't close issue like that.

**Comment by talregev** [comment] 2021-09-09 19:27
@natebosch Please open this issue. My issue is on `Content-Length:` and not about `preserveHeaderCase`

**Comment by talregev** [comment] 2021-09-09 19:28
There isn't `Content-Length:` on http `dart.library.io`. Please fix it.

**Comment by natebosch** [comment] 2021-09-09 20:11
> also if force all the header to be lowercase, while http header is sensitive case.
> This break the connection to legacy http server that expect the `Content-Length:` field in the header, while looking it as sensitive way. (exact as I write it). also looking other fields header in sensitive way.

This is the buggy server behavior which `preserveHeaderCase` is designed to work around. The HTTP spec states that headers are case insensitive, and so for a long time all HTTP requests in Dart used lowercase headers. For backwards compatibility we added an argument to override that when setting a header through `dart:io`, but we don't have that support here. https://api.dart.dev/stable/2.14.1/dart-io/HttpHeaders/set.html

You can use `dart:io` direclty to work around this in the meantime.

> There isn't Content-Length: on http dart.library.io. Please fix it.

There may be some browser behavior coming in to play. I'm not aware of any intentional differences between when we will and won't automatically add the content length header. Can you post a specific minimal reproduction case where we add a content length header on the web but not on the VM?

**Comment by talregev** [comment] 2021-09-10 07:24
Why I need to do heavy lifting for you, to do some simple check?
Any post request that you do from `dart.library.io` are missing the field in the header of `Content-Length:`
Do http request from `dart.library.io` and from `dart.library.html` Diagnose it with postman (or other apps). 
And see yourself the differences. 
@natebosch 
Did you check your own code before requesting minimal example?

**Comment by talregev** [comment] 2021-09-10 19:28
Did you change something from my last check? If yes, I will need to check it again. 
What happen if you add the `preserveHeaderCase`
Did it change to `Content-Length:`?

**Comment by natebosch** [comment] 2021-09-10 19:39
> What happen if you add the `preserveHeaderCase`
> Did it change to `Content-Length:`?

No, it would not automatically become `Content-Length:` using that argument. If we add that argument it would allow you to manually set a `Content-Length:` header and we wouldn't overwrite it or change it to lowercase.

**Comment by talregev** [comment] 2021-09-10 19:40
> wouldn't overwrite it or change it to lowercase

Can you fix that?
