### ISSUE TITLE
No address associated with hostname

### ISSUE THREAD

**Issue by techyrajeev** [dart-lang/http#185] opened 2018-07-23 13:06 UTC
Getting this error while calling api.

Sometimes I receive response occasionally. I tested the api using postman it is working perfectly fine.
Version: http: ^0.11.3+16
`
[ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (24807): SocketException: Failed host lookup: 'api.xyz.com' (OS Error: No address associated with hostname, errno = 7)
E/flutter (24807): #0      IOClient.send (package:http/src/io_client.dart:30:23)
E/flutter (24807): <asynchronous suspension>
E/flutter (24807): #1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:171:38)
E/flutter (24807): <asynchronous suspension>
E/flutter (24807): #2      BaseClient.post (package:http/src/base_client.dart:56:5)
E/flutter (24807): #3      post.<anonymous closure> (package:http/http.dart:70:34)
E/flutter (24807): #4      _withClient (package:http/http.dart:167:20)
E/flutter (24807): <asynchronous suspension>
E/flutter (24807): #5      post (package:http/http.dart:70:3)
E/flutter (24807): #6      NetworkUtil.post (package:ddictor/utils/network_util.dart:29:10)
E/flutter (24807): #7      loginUser (package:ddictor/utils/api.dart:23:16)
`

post method inside network_util file

`
   Future<dynamic> post(String url, {Map headers, body, encoding}) {
    return http
        .post(url, body: body, headers, encoding: encoding)
        .then((http.Response response) {
      final String res = response.body;
      final int statusCode = response.statusCode;

      if (statusCode < 200 || statusCode > 400 || json == null) {
        throw new Exception("Error while fetching data");
      }
      return _decoder.convert(res);
    });
  }

**Comment by cskau-g** [comment] 2018-08-23 12:02
The errors `Failed host lookup: 'api.xyz.com'` and `OS Error: No address associated with hostname` usually mean that your DNS lookup fails.
As hinted by `OS Error` this is usually a system-level error and nothing specific to `http` or Dart.

To diagnose this on your system you can try check e.g. your browser can DNS resolve the host in question. And/or if you're on a Mac/Linux system you might be able to run `dig api.xyz.com` to see if that resolves.

When doing anything network, or I/O in general, it's a good idea to program very defensively and assume the I/O can sporadically fail or time out.
You can try see if you can make your code degrade more gracefully in cases when e.g. DNS isn't working as expected.


I'll go ahead and close this issue since I don't think there's anything to be done in `http`

**Closed by cskau-g** 2018-08-23 12:02 UTC

**Comment by gurgenDP** [comment] 2019-03-01 20:48
Anyone facing this issue: try adding ` <uses-permission android:name="android.permission.INTERNET" /> ` to your AndroidManifest.xml.

**Comment by aidooyaw1992** [comment] 2019-03-20 17:07
thank you, this worked for me

**Comment by NataliaPena** [comment] 2019-05-28 19:03
I had the same error. In my case it was because the emulator of the phone that I am using does not have access to the internet.

Run the application on a physical mobile device and it worked immediately.

Solution connect the emulator to the internet.

**Comment by Svoka** [comment] 2019-06-07 13:11
I think we need to add message that you need to add internet permission in Install section of doc

**Comment by natebosch** [comment] 2019-06-07 19:51
> I think we need to add message that you need to add internet permission in Install section of doc

Please +1 and follow https://github.com/flutter/flutter/issues/29688

If we have some flutter docs to point to from this README we can do that.

**Comment by Derkin** [comment] 2019-09-04 09:30
I have the same issue when run in release mode,but it is ok when debug mode !

**Comment by natebosch** [comment] 2019-09-04 17:38
@Derkin - please raise the issue at flutter/flutter#29688

This isn't a problem that can be solved in this package.

**Comment by balajiks-dev** [comment] 2019-09-25 08:37
Hi,
This error is because if your Simulator or Your phone doesn't connect to the Internet.

**Comment by Abdusin** [comment] 2019-10-23 17:00
> Anyone facing this issue: try adding `<uses-permission android:name="android.permission.INTERNET" />` to your AndroidManifest.xml.

@gurgenDP pls help me this way dont solve my problem
[flutter/flutter/#43357](https://github.com/flutter/flutter/issues/43357)

**Comment by sdnuliu** [comment] 2019-11-20 06:53
I have the same issue when run in release mode,but it is ok when debug mode ! my api address like "www.xxx.com/xx/xxx", after i remove "www" use "xxx.com/xx/xxx",solve the problem,but i am confused why?

**Comment by TomOerlemans** [comment] 2019-11-26 16:13
Just ran into this issue. After about half an hour I finally figured out that it was because I had my VPN on..

**Comment by jawale204** [comment] 2019-12-11 07:00
> I have the same issue when run in release mode,but it is ok when debug mode !

 i have same issue with my app . So have u figured it out now???

**Comment by natebosch** [comment] 2019-12-11 23:39
@jawale204  - please raise the issue at flutter/flutter#29688

This isn't a problem that can be solved in this package.

**Comment by dsouzajaison** [comment] 2020-03-03 23:17
> > I have the same issue when run in release mode,but it is ok when debug mode !
> 
> i have same issue with my app . So have u figured it out now???

This error is because if your Simulator or Your phone doesn't connect to the Internet.

**Comment by gulmensedat** [comment] 2020-08-03 08:29
I made new minor sdk updates, upgraded the http package, closed the emulator and re-opened it, and stopped the application and re-compiled the problem was fixed.

**Comment by 1pavanb** [comment] 2020-08-08 16:49
> The errors `Failed host lookup: 'api.xyz.com'` and `OS Error: No address associated with hostname` usually mean that your DNS lookup fails.
> As hinted by `OS Error` this is usually a system-level error and nothing specific to `http` or Dart.
> 
> To diagnose this on your system you can try check e.g. your browser can DNS resolve the host in question. And/or if you're on a Mac/Linux system you might be able to run `dig api.xyz.com` to see if that resolves.
> 
> When doing anything network, or I/O in general, it's a good idea to program very defensively and assume the I/O can sporadically fail or time out.
> You can try see if you can make your code degrade more gracefully in cases when e.g. DNS isn't working as expected.
> 
> I'll go ahead and close this issue since I don't think there's anything to be done in `http`

that was valuable insight, thanks @cskau-g man.I was worried about this issue.
It was DNS, I was messing with my DNS settings.

people kept spamming about the missing Internet Permission. That wasn't my case.
It was hard to find this info. I'll set the DNS to default settings and see if it's resolved.

thanks again! 👍🤝

**Comment by aloev** [comment] 2020-09-03 18:41
> I had the same error. In my case it was because the emulator of the phone that I am using does not have access to the internet.
> 
> Run the application on a physical mobile device and it worked immediately.
> 
> Solution connect the emulator to the internet.

This solved the issue for me. Thanks a lot!

**Comment by alokkumax** [comment] 2020-11-01 09:16
> @jawale204 - please raise the issue at flutter/flutter#29688
> 
> This isn't a problem that can be solved in this package.

step 1
add 
<uses-permission android:name="android.permission.INTERNET" />
to you androidmanifest, if done,
step 2
connect your emulator to a internet, if you cant use in on your physical device

**Comment by gitayanbhat** [comment] 2020-11-19 12:32
> Anyone facing this issue: try adding `<uses-permission android:name="android.permission.INTERNET" />` to your AndroidManifest.xml.

HAVE TRIED THE ABOVE BUT THE SAME ERROR EXISTS PLS HELP....

**Comment by jaiwaikhom** [comment] 2020-12-15 02:32
I am also facing the same error after doing all the steps mentioned above. Please suggest.

**Comment by gitayanbhat** [comment] 2020-12-15 02:45
Failed Host Lookup error occurs when their is no internet connection in the AVD in the laptop...... Suggestion is to close the AVD, check your internet connection and then open your AVD and then run again......

Also if their is a problem in the API itself the. This error might occur..........

**Comment by gitayanbhat** [comment] 2020-12-15 02:45
That's how I did solve it...

**Comment by alokkumax** [comment] 2020-12-15 15:32
Just restart the emulator that's it

**Comment by abdesselam-benameur** [comment] 2021-01-01 14:08
I had this issue and the cause of this error for me was that my phone was not connected to the internet 🤦‍♂️

**Comment by mariokresic** [comment] 2021-01-14 10:42
I've faced this issue after trying to build my flutter apk for the first time, with the intention to test it on a real android device. 

After building, the issue occurred on both devices (real and emulator).

- There are a couple of AndroidManifest.xml in my project, and they all contain `<uses-permission android:name="android.permission.INTERNET" />` . 
- Both real device and emulator phones were connected to the internet so that wasn't the problem.

What helped was reinstalling the http package.

**Comment by JoyEnergiser** [comment] 2021-01-20 14:41
> Just ran into this issue. After about half an hour I finally figured out that it was because I had my VPN on..

Thanks you are my hero! same issue hehe

**Comment by Zaid101** [comment] 2021-02-09 19:01
my problem was with the api url it was inccorect.

**Comment by asbansal** [comment] 2021-02-10 13:00
In my real android device, it is NOT working with **Jio** internet. With airtel and other networks, it's working fine. Do telecom operators put proxy etc. in the http requests?

**Comment by gururaja-kambala** [comment] 2021-02-21 10:11
> In my real android device, it is NOT working with **Jio** internet. With airtel and other networks, it's working fine. Do telecom operators put proxy etc. in the http requests?

For our app users using **Jio** network this issue happens some times. On same device it works some time, and does not work some time. Server has ipv4-only ip. Only A record is set on DNS server.

**Comment by asbansal** [comment] 2021-02-21 11:11
> > In my real android device, it is NOT working with **Jio** internet. With airtel and other networks, it's working fine. Do telecom operators put proxy etc. in the http requests?
> 
> For our app users using **Jio** network this issue happens some times. On same device it works some time, and does not work some time. Server has ipv4-only ip. Only A record is set on DNS server.

I solved it by changing api url. Jio uses some SNI url filtering mechanism. 

https://cis-india.org/internet-governance/blog/reliance-jio-is-using-sni-inspection-to-block-websites .

So for some reason my previous api endpoint was not being hit.

**Comment by errorsolve** [comment] 2021-03-01 17:25
[[Solved] How to solve SocketException: Failed host lookup: ‘flutter-project-xxxxx.firebaseio.com’ (OS Error: No address associated with hostname, errno = 7)
](https://fluttercorner.com/how-to-solve-socketexception-failed-host-lookup-www-xyz-com-os-error-no-ad/)

**Comment by Shybeen** [comment] 2021-05-14 17:50
> Hi, yes its correct, thank you
> This error is because if your Simulator or Your phone doesn't connect to the Internet.

**Comment by Mohamed-Reda1010** [comment] 2023-05-27 02:55
i tried every thing , nothing work !!

**Comment by dhruv-kabariya** [comment] 2024-06-27 00:36
> > > In my real android device, it is NOT working with **Jio** internet. With airtel and other networks, it's working fine. Do telecom operators put proxy etc. in the http requests?
> > 
> > For our app users using **Jio** network this issue happens some times. On same device it works some time, and does not work some time. Server has ipv4-only ip. Only A record is set on DNS server.
> 
> I solved it by changing api url. Jio uses some SNI url filtering mechanism. 
> 
> https://cis-india.org/internet-governance/blog/reliance-jio-is-using-sni-inspection-to-block-websites .
> 
> So for some reason my previous api endpoint was not being hit.

Can you tell me what exactly you did. Because I am facing same issue

**Comment by dhruv-kabariya** [comment] 2024-06-27 00:36
> > In my real android device, it is NOT working with **Jio** internet. With airtel and other networks, it's working fine. Do telecom operators put proxy etc. in the http requests?
> 
> For our app users using **Jio** network this issue happens some times. On same device it works some time, and does not work some time. Server has ipv4-only ip. Only A record is set on DNS server.

What is solution then ?

**Comment by qhmd** [comment] 2025-06-22 06:26
in my case, there dns active in my phone, so, i turn off the dns in the setting and its finally working
