### ISSUE TITLE
Invalid Internet Address

### ISSUE THREAD

**Issue by SandorSzavost28** [dart-lang/http#935] opened 2023-05-17 15:54 UTC
https://github.com/flutter/flutter/issues/126650

After upgrading Flutter 3.10.0 users have been getting Invalid Internet Address Error when requesting with http. 

Issue explained on detail on URL above. Is it http package related to this? thanks!

![imagen](https://github.com/dart-lang/http/assets/37272894/021138d1-4d47-45d5-a463-9db9c9913e34)

**Comment by DanTup** [comment] 2023-05-18 09:38
@natebosch noted at https://github.com/flutter/flutter/issues/126650#issuecomment-1548613847, this isn't related to package:http. It happens using the SDK APIs directly.

The issue is that you have "All Exceptions" ticked in the debugger, meaning that the debugger will pause on _any_ thrown exception even when it will be caught. If you click "continue" you'll see the web request completes normally and your app does not produce any errors. I would recommend instead only ticking "Uncaught exceptions" because I think provides the behaviour you're expecting.

I included some more details about this in https://github.com/flutter/flutter/issues/126650#issuecomment-1547909038 and https://github.com/flutter/flutter/issues/126650#issuecomment-1551004871.

I've also opened https://github.com/dart-lang/sdk/issues/52423 to enquire whether the SDK could be tweaked to avoid this situation. However it's not itself a bug, and if you run with "All Exceptions" ticked you should always be prepared that the debugger will stop on exceptions that are not actual errors you need to handle/fix.

**Comment by brianquinlan** [comment] 2023-06-01 00:46
This will also be fixed in Dart 3.0.3.

**Closed by brianquinlan** 2023-06-01 00:46 UTC
Labels: type-bug, package:http
