### ISSUE TITLE
Works on the mobile but not on the web

### ISSUE THREAD

**Issue by saadjavaidalvi** [dart-lang/http#380] opened 2020-02-12 09:20 UTC
*** Here is the link to the API that i am trying to access on the flutter web with the 'GET' request:
https://cowork.pk/rest/session/token

*** The API totally gives the result when on the mobile
*** Gives error when accessing with the flutter web
*** On flutter web when getting the GET request it catches in try catch and gives error of XMLHTTPREQUEST error

Here is the code I am using for this:

import 'package:http/http.dart' as https;

try {
      var data;
      var statusCode;
      var response = await https.get(url);
      statusCode = response.statusCode;
      if(response.statusCode == 200)
      {
        data = jsonDecode(response.body);
        // data = jsonDecode(reply);
       return data 
      }
      else{
        return null;
      }

    } catch (ex) {
      print(ex);
      return null;
    }

**Comment by natebosch** [comment] 2020-02-13 01:37
This is most likely a browser restriction like CORS. If you inspect the XMLHTTPRequest when it is thrown you may be able to get more details.

I'll close this issue for now since it is unlikely to be related to this library. If you believe it is caused specifically by a bug in this package (IE it does not reproduce if you use `HttpRequest` from `dart:html` directly, https://api.dart.dev/stable/2.7.1/dart-html/HttpRequest-class.html) we can reopen and investigate.

**Closed by natebosch** 2020-02-13 01:37 UTC
