### ISSUE TITLE
Connection closed before full header was received

### ISSUE THREAD

**Issue by samsoft00** [dart-lang/http#246] opened 2019-02-23 18:05 UTC
https://stackoverflow.com/questions/54844472/flutter-dart-http-connection-issue

**Comment by joe-rocko** [comment] 2019-07-24 15:58
I'm having a similar issue.

**Comment by natebosch** [comment] 2019-07-24 19:50
It looks like this exception is coming from `dart:io`, not this package.

I'm going to close this issue since it doesn't have enough information for us to investigate. If you can stably reproduce this behavior we can file an issue against the SDK and dig from there. Most likely this is a result of some behavior of the server.

**Closed by natebosch** 2019-07-24 19:50 UTC
