### ISSUE TITLE
Not working for localhost URLs on Android

### ISSUE THREAD

**Issue by IrosTheBeggar** [dart-lang/http#233] opened 2019-01-24 22:59 UTC
I was successfully able to call my localhost url: `http://localhost:3030/ping` on iOS, but the same code threw and error on Android:

My code
```
    String thisUrl = 'http://localhost:3030/ping';
    try {
      var response = await http.get(thisUrl);
    } catch(err) {
      Scaffold.of(context).showSnackBar(SnackBar(content: Text('Could not connect to server')));
      return;
    }
```

**Comment by natebosch** [comment] 2019-01-24 23:13
What is the error?

Is the server running?

**Comment by IrosTheBeggar** [comment] 2019-01-25 03:56
The server is running.  I can call is successfully on iOS.  I get this error on Android:

```
SocketException (SocketException: OS Error: Connection refused, errno = 111, address = localhost, port = 59278)
```

The weird thing is the url is for port 3030 but that error says the port is 59278.

**Comment by avimak** [comment] 2019-07-29 06:42
same here, running a local server on `localhost:3001`, tried accessing it from Android emulator using both `http://localhost:3001` and `http://127.0.0.1:3001`, yet i'm getting the following error:
```
SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 52424
```
note the port (!?)

**Comment by avimak** [comment] 2019-07-29 06:47
try using your machine's network IP, i.e. `http://192.168.1.11:3030`

**Comment by MansurAliKoroglu** [comment] 2019-07-30 15:30
To connect your localhost (127.0.0.1) with android emulator devices you should use http://10.0.2.2/

**Comment by natebosch** [comment] 2019-07-30 17:39
@IrosTheBeggar - the strange looking port is caused by https://github.com/dart-lang/sdk/issues/12693

Closing the remainder of this issue as a duplicate of https://github.com/flutter/flutter/issues/29688 since flutter should own the documentation for using http in a flutter application and emulator.

**Closed by natebosch** 2019-07-30 17:39 UTC
