### ISSUE TITLE
Content-Type header is changed to be lower case, causing PATCH requests to fail

### ISSUE THREAD

**Issue by Fnalsk** [dart-lang/http#615] opened 2021-09-06 10:59 UTC
My backend is using Flask rest JSON API. I'm trying to send a PATCH request to modify something in my database.

I tested this locally with cURL and it works as expected. However when I send the same request in Flutter to my backend server, I get a 415 error code with message "Content-Type header must be application/vnd.api+json", despite setting that header correctly. 

Checking the code for Flask rest JSON API, I found that the `check_headers` decorator is responsible for this. However it checks for `Content-Type`, with upper case letters. If the header contains `content-type` instead, one will get the error I'm getting.

This isn't something wrong with Flask rest JSON API, since the documentation for that necessitates that the `Content-Type` header must indeed be set to the above value. 

According to [this](https://stackoverflow.com/questions/55893376/flutter-content-type-must-be-application-json), the http library converts headers to lower case, which causes this problem. I'd like for this library to send all headers as is, without changing the case.

**Comment by natebosch** [comment] 2021-09-09 19:23
Closing as a duplicate of #609 which is a feature request for a `preserveHeaderCase` feature.

> This isn't something wrong with Flask rest JSON API, since the documentation for that necessitates that the `Content-Type` header must indeed be set to the above value.

The HTTP protocol specifies that header names are case insensitive. This is a bug in the server and probably worth filing an issue.

In the meantime the workaround for communicating with buggy servers is to use the `HttpClient` from `dart:io` directly and pass the `preserveHeaderCase` argument when setting the header value.

**Closed by natebosch** 2021-09-09 19:23 UTC
