### ISSUE TITLE
Digest authentication returns always 401

### ISSUE THREAD

**Issue by BigGitWorld** [dart-lang/http#605] opened 2021-08-04 21:07 UTC
Hello!
I'm a JAVA developer and want to connect to a local digest http server in a flutter (android) app.
I have implemented rfc7617 in java and it works correctly by any java http client (like apache http client, google http client and etc).
Now I want to implement it in dart. So I wrote the below code :
```
void callAPI(String ip) async { //ip=192.168.1.101

  var request1 = http.Request('GET', Uri.parse('http://' + ip + '/api/state'));
  http.StreamedResponse response1 = await request1.send();

  if (response1.statusCode == 401) {
    print("reason1:" + response1.reasonPhrase!);

    DigestAuth _auth = DigestAuth("admin", "admin");
    final String? authInfo = response1.headers["www-authenticate"];
    _auth.initFromAuthorizationHeader(authInfo!);
    String newAuthHeader = _auth.getAuthString();

    var headers = {
      'Authorization': newAuthHeader
    };

    var request2 = http.Request('GET', Uri.parse('http://' + ip + '/api/state'));
    request2.headers.addAll(headers);
    http.StreamedResponse response2 = await request2.send();
    print("code:" + response2.statusCode.toString()); //returns 401 always
  }
}
```
DigestAuth class
```
class DigestAuth {

  DigestAuth(this.username, this.password);

  String realm = "Protected";
  String uri = "/api/state";
  String qop = "auth";

  String? username;
  String? password;
  String? nonce;

  String _computeCnonce() {
    math.Random rnd = math.Random();
    List<int> values = List<int>.generate(16, (i) => rnd.nextInt(256));
    return hex.encode(values);
  }

  String getAuthString() {
    String cnonce = _computeCnonce();
    var nc = 1; //I know it have to increase by every request, but I have only one request here.
    final nonceCount = _formatNonceCount(nc);

    String ha1 = md5Hash("$username:$realm:$password");
    String ha2 = md5Hash("GET:$uri");
    String rsp = md5Hash("$ha1:$nonce:$nonceCount:$cnonce:$qop:$ha2");

    return 'Digest username="$username", realm="$realm", nonce="$nonce", uri="$uri", qop=$qop, nc=$nonceCount, cnonce="$cnonce", response="$rsp"';

  }

  void initFromAuthorizationHeader(String authInfo) {
    Map<String, String> values = splitAuthenticateHeader(authInfo)!;
    nonce = values['nonce'];
  }


 Map<String, String>? splitAuthenticateHeader(String? header) {
  if (header == null || !header.startsWith('Digest ')) {
    return null;
  }
  String token = header.substring(7); // remove 'Digest '
  print("token(after 'Digest '):" + token);
  var ret = <String, String>{};

  final components = token.split(',').map((token) => token.trim());
  for (final component in components) {
    final kv = component.split('=');
    ret[kv[0]] = kv.getRange(1, kv.length).join('=').replaceAll('"', '');
  }
  return ret;
}

}

```

while if I copy the genereated ``newAuthHeader`` variable to the java code and only replace ``nonce, response`` values programmatically, java code works correctly and receive 200 status code.

I have used different http packages in dart, but always get 401!
what is the problem?

Flutter 2.2.1
Framework • revision 02c026b03c (10 weeks ago) • 2021-05-27 12:24:44 -0700
Engine • revision 0fdb562ac8
Tools • Dart 2.13.1

**Comment by BigGitWorld** [comment] 2021-08-10 08:36
I opened a similar issue in the [http_auth flutter package](https://github.com/marcoesposito1988/http_auth/issues/12) also.
You can see my JAVA code that works perfectly. But my dart code returns 401 always.

**Comment by natebosch** [comment] 2021-08-16 22:59
Can you describe the difference between the request made by `package:http` and the requests that are successful? Do you believe that something in this library is changing the request in an undesired way? Does it have something to do with header name capitalization?

**Comment by BigGitWorld** [comment] 2021-08-31 15:31
There is not any difference between request created by JAVA and Dart.
1. send a simple http GET request to server and get 401 response with a www-authenticate header like the below:
```
Digest realm="Protected", qop="auth", nonce="460ed2cc4ce65a9f", opaque=""
```

2. create nonce, response and other parameters and add "Authorization" header like the below to the request :
```
Digest username="admin", realm="Protected", nonce="460ed2cc4ce65a9f", uri="/api/state", qop=auth, nc=00000001, cnonce="38d9300fd154b82e", response="2ff459439b6151e55408263f39f74bde"
```
3. Send again request with the new "Authorization" header to my server.

result:
JAVA code works perfectly.
Dart code returns 401 again!

 I do not know what is problem! :(

**Comment by natebosch** [comment] 2021-08-31 16:03
> There is not any difference between request created by JAVA and Dart.

There must be some difference or the server would not treat them differently. Can you investigate the difference that the server side sees?

> Dart code returns 401 again!

The _server_ is what sends the status code.

**Comment by natebosch** [comment] 2021-08-31 16:05
> In debug mode, I see my header (Authentication: Digest ...) is incomplete and it seems header size is limited in dart http clients.

How do you see this? Can you provide a complete minimal reproduction case demonstrating when the authentication header is corrupted by `package:http` or the Dart SDK?

**Comment by natebosch** [comment] 2021-09-09 20:02
My best guess on this is the server is buggy and relies on a specific capitalization of the header (which should be case insensitive). I'll close this as a duplicate of #609 

In the meantime, if it is header name capitalization the workaround is to use the client from `dart:io` directly and pass the `preserveHeaderCase` argument.

**Closed by natebosch** 2021-09-09 20:02 UTC
Labels: need-info

**Comment by edufolly** [comment] 2024-01-12 14:53
I found the same problem with Mikrotik switch. The switch does not accept lowercase header keys. http always use `authorization` instead of `Authorization`.
