### ISSUE TITLE
about self define Response headers

### ISSUE THREAD

**Issue by zhouxingtuan** [dart-lang/http#363] opened 2020-01-13 15:08 UTC
Response headers in the package http parse the 'content-length, content-type' only. Will it support to parse all the return headers, like self define header 'XXX: YYY'?

**Comment by natebosch** [comment] 2020-01-13 23:40
The `Response` object has a `headers` field which should include all headers received.

For instance if I do:

```dart
var response = await http.get('https://www.google.com');
print(response.headers);
```

Then I see a bunch of  headers starting with `x-google-`.

Do you have a minimal repro where the headers don't show up?

**Comment by zhouxingtuan** [comment] 2020-01-14 03:03
`Uint8List responseBody;
    String url1 = "https://space0x0.com/touch/";
    int msgID1 = 0x1004;
    String body1 = "";
    try {
      Map<String, String> postHeaders = new Map<String, String>();
      postHeaders["Message"] = msgID1.toString();
      var response = await http.post(url1, headers: postHeaders, body: body1);
      response.headers.forEach((k, v){
        print(k + " " + v);
      });
      if (response.statusCode == HttpStatus.ok) {
        responseBody = response.bodyBytes;
      } else {
        print('Error post request Http status ${response.statusCode}');
      }
    } catch (exception) {
      print('Failed getting IP address ' + exception.toString());
    }`
wait for about 10 seconds, the server will return error. I saw the response headers in chrome, but can't print them int the code.

**Comment by natebosch** [comment] 2020-01-14 03:54
When pasting code snippets into comments you can use a triple backtick at the start and end to create a [code fence](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks)

When I run this example I see headers on the VM.

```
connection keep-alive
test Hello World!
accept-ranges bytes
date Tue, 14 Jan 2020 03:51:12 GMT
access-control-allow-origin *
content-length 29
content-type text/html; charset=utf-8
server nginx/1.17.7
```

**Comment by zhouxingtuan** [comment] 2020-01-14 05:38
I see. It works well on Android and IOS, but not on the flutter web.

**Comment by natebosch** [comment] 2020-02-12 23:56
> It works fine on Android and IOS, but not on the flutter web.

That is caused by the browser. See https://stackoverflow.com/a/22718272/374798

My understanding is that the server side needs to send that header. Since this is a browser level restriction I don't think there is anything we can do on the Dart side to impact this behavior. I'll close the issue for now.

**Closed by natebosch** 2020-02-12 23:56 UTC
Labels: need-info, question
